### ISSUE TITLE
Creator Onboarding Page

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#14645]
**📖 As an admin or Forem creator, I want to set up the mandatory configuration after sign up, to be able to get my Forem up and running.** 

_(Format:  As a [persona], I [want to], [so that])_

![](https://user-images.githubusercontent.com/108287/116532347-6d033700-a8e0-11eb-8dae-88bf6164f682.png)

**🐣TASKS**

- [x] Add the "Community Name" field to the form
- [x] Add the "Upload an image" button to the form
- [x] Add the "Brand Color" hex color picker to the form
- [x] Add the "Who can join the community?" radio buttons to the form 
- [x] Add the "Who can view content on this community?" radio buttons to the form
- [ ] Ensure that the "Help" icon shows in the bottom righthand corner of the form
- [x] Ensure that as fields are updated, the form itself is updated (see linked RFC section for reference) 

**OTHER NOTES** 
Please see [this](https://github.com/forem/rfcs/blob/a8d843d9a37c4105850f575f6e51faac7377a474/text/0190-admin-onboarding.md#step-3-set-up-forem) section of the RFC for more information on what needs to be accomplished.
