### ISSUE TITLE
Creator Signup Page

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#14647]
**📖 As an admin or Forem creator, I want to be able to easily sign up for my Forem, so that I can start building my community** 

_(Format:  As a [persona], I [want to], [so that])_

![](https://camo.githubusercontent.com/9bb071ae5d6aef1cf6148de3caf64a169a9e4248be70c2c1c65a2b216a7c3071/68747470733a2f2f63646e2d7374642e64726f706c722e6e65742f66696c65732f6163635f3638303736312f5754454a3065)

**🐣TASKS**

- [x] Update style and copy
- [x] Add JS Validation 
- [x] Drop the image field and add an image placeholder on the backend
- [x] Update the interaction states
- [x] Add suggested username 
- [x] Add a masked password field
