### ISSUE TITLE
General Workflow for Creator Signup & Onboarding 

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#14649]
**📖 As an admin or Forem creator, I want to be distraction free when signing up and onboarding, so that I can focus on the task at hand.** 

_(Format:  As a [persona], I [want to], [so that])_

![](https://user-images.githubusercontent.com/108287/116532363-712f5480-a8e0-11eb-9ef0-a397c5c3c4ef.png)

**🐣TASKS**

- [x] Remove the header and the footer on signup page 
- [x] Remove the header and the footer on confirmation page 
- [x] Remove the header and the footer on creator settings page 

As per the RFC:
```
It's worth noting that we are introducing a layout change; we will no longer show classic app's structure (with header etc.)

So the idea is to get rid of any decorations, drop the current app's structure and focus only on what's crucial for admins to set up their Forem.

Creating new layout will require creating a new layout view in the codebase, a layout without header, footer, etc.

From a technical standpoint, this will require creating a new view that does not include the header or footer (we will need to extract out the header/footer and render it conditionally in "normal" mode, rather than in "setup" mode).

Forem Admins should not be able to view any part of the Forem until they have completed the onboarding process. In other words, they should be able to see Forem's home page (and other pages) once they click the Finish button on the last step.

From a technical standpoint, we will need to ensure that there are no links from the "setup"/onboarding view to anywhere else on the Forem, and that every Forem admin is always redirected to setup if they haven't completed it yet.
```

- [x] Do not allow navigation to any other page until onboarding is complete

**Comment by Ridhwana** [comment]
@juliannatetreault looking for my next issue so just want to double check if you've started working on this issue or if I could tackle it?

**Comment by juliannatetreault** [comment]
Thanks for checking in with me--I appreciate it! Feel free to tackle this one, @Ridhwana. 😊

**Comment by Ridhwana** [comment]
I've started a slack conversation to gain some thoughts and insights from others: https://forem-team.slack.com/archives/C01S4QZUDNC/p1632137443006500
