### ISSUE TITLE
Email Confirmation Page

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#14648]
**📖 As an admin or Forem creator, when my SMTP is enabled I want to see an email confirmation page, to ensure that nobody can just log into my Forem.** 

_(Format:  As a [persona], I [want to], [so that])_

![](https://camo.githubusercontent.com/8b118a4cc13bf94cdf97956c508d3c9abda5746a21e13fd46301cc1e42c1d6c0/68747470733a2f2f63646e2d7374642e64726f706c722e6e65742f66696c65732f6163635f3638303736312f664c68595848)
![](https://camo.githubusercontent.com/d8b3119cfd041972c9526dc8b3f18fba6404fe80138f2525901b4cb247a29150/68747470733a2f2f63646e2d7374642e64726f706c722e6e65742f66696c65732f6163635f3638303736312f6d4736516250)

**🐣TASKS**

- [x] Update style and copy of page 
- [x] Add a modal to resend the confirmation
- [x] Only show this page if SMTP is configured. [See more](https://github.com/forem/rfcs/pull/190#issuecomment-834729917)

**Comment by Ridhwana** [comment]
This task is already complete but @juliannatetreault brought up some thought provoking questions which I'd like to discuss: 

Some context:
>  Admins/Forem Creators are already logged in regardless of whether they confirm their email or not because we allow it to be skippable, so my thought was that it may be unnecessary for us to even show an email confirmation page if this is the case.

**I dug more into this and here are my findings:**

If we look at the [code for the `create` method in the registrations controller](https://github.com/forem/forem/blob/main/app/controllers/registrations_controller.rb#L14-L36):

We will see that in the [update_first_user_permissions method](https://github.com/forem/forem/blob/main/app/controllers/registrations_controller.rb#L14-L36), we say `resource.skip_confirmation` which does skips sending the confirmation on create.

However, further down, we say if `SMTP_enabled` then we redirect to the confirmation page. This is because when SMTP is enabled [then confirmation is actually required](https://github.com/forem/forem/blob/main/app/models/user.rb#L662)
(I'm not actually sure does the `resource.skip_confirmation` (from `update_first_user_permissions` method) override this in any way when the resource is persisted)

```
  def confirmation_required?
    ForemInstance.smtp_enabled?
  end
```

[This callback above](https://www.rubydoc.info/github/plataformatec/devise/Devise%2FModels%2FConfirmable:confirmation_required%3F) in the User model is to overwrite whether confirmation is required or not. 

SMTP may be enabled prior to a creator signing in, if for instance the creator had setup their SMTP  via environment variables or perhaps in the future we would have set it up via env variables for Forem Cloud (prior to them logging in)

Now taking this one step further, we have [this issue](https://github.com/forem/forem/issues/14652) that specifies that in the instance where a confirmation email gets sent to a Forem Creator then clicking on the confirmation link should allow the creator to log right in. This still needs to be implemented.

@maestromac I know that we chatted about something similar a while back and I'm paraphrasing from that context. Based on your experience working on the code, does this sound accurate or am I perhaps misunderstanding something?

**Comment by maestromac** [comment]
@Ridhwana there's no overwritten involved; If the code `resource.skip_confirmation` was hit, the user is already confirmed. Redirecting users to their confirmation page is just a page redirect and has nothing to do with whether or not the user is already email confirmed. 

A confirmation email will still get sent out though, if SMTP is enabled. It's just like how it is with [DEV right now](        user.skip_confirmation!). We don't need any of our users to confirm their email when they sign up but they will still receive an email pretending that they need to confirm. I can only guess it's because if users enter via Github or Twitter, they are technically already validated.
