### ISSUE TITLE
Interaction and Styling on the Creator Onboarding Page

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#14646]
**📖 As an admin or Forem creator, I want to see how my updated configuration will affect my Forem UI, so that I can provide the best UI to my users** 

_(Format:  As a [persona], I [want to], [so that])_

![](https://user-images.githubusercontent.com/108287/116532363-712f5480-a8e0-11eb-9ef0-a397c5c3c4ef.png)

**🐣TASKS**
https://github.com/forem/rfcs/blob/a8d843d9a37c4105850f575f6e51faac7377a474/text/0190-admin-onboarding.md

- [ ] When the admin updates the brand color, then update the accent color on all elements on the page
        - [ ]  buttons 
        - [ ] radio buttons accents
        - [ ] Forem Background 
        - [ ] Help Icon
        - [ ] text field accent
         i.e. buttons, active elements, forem background image. Resource [JS & CSS](https://css-tricks.com/updating-a-css-variable-with-javascript)

**Comment by Ridhwana** [comment]
Quick question here @juliannatetreault: Have we added validation that the logo has a minimum size of 300x300 pixels?

**Comment by Ridhwana** [comment]
Being playing aorund with this: 
https://css-tricks.com/updating-a-css-variable-with-javascript/

let root = document.documentElement;
root.style.setProperty('--radius', "150px"); //substitue with color

**Comment by juliannatetreault** [comment]
> Quick question here @juliannatetreault: Have we added validation that the logo has a minimum size of 300x300 pixels?

Great question! We have not, @Ridhwana
