### ISSUE TITLE
Provide Forem's Policies During the Creator Onboarding Flow

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#15081]
📖  **As a Forem creator, I want to be able to be to read and acknowledge the Privacy Policy, Acceptable Use Policy, agree to remove user data when requested, etc. during the onboarding process, so that I can proceed to use Forem's software in an appropriate way.**

(Format: As a [persona], I [want to], [so that])

**🐣TASKS**

- [ ] Add the Privacy Policy to the Creator Onboarding Flow
- [ ] Add the Acceptable Use Policy to the Creator Onboarding Flow
- [ ] Add an agreement for the removal of user data upon request to the Creator Onboarding Flow

**Comment by mikeydorje** [comment]
Creator onboarding includes required acknowledgements for Code of Conduct and Terms, but this issue also requests explicit Privacy Policy, Acceptable Use Policy, and user-data-removal agreement steps, which are not clearly present as separate onboarding acknowledgements in current flow.
