### ISSUE TITLE
Update the Creator Settings Page UI 

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#15524]
**📖  As a Forem Creator, I want my experience to be as UI pleasing as possible, so that I feel motivated to continue with the journey.** 

_(Format:  As a [persona], I [want to], [so that])_

![Frame 446](https://user-images.githubusercontent.com/32834804/143931992-b01e9bbb-7aaa-448f-8f06-87a1fa27a7ae.png)

**🐣TASKS**

- [x] Update the radio button styling per the above design (@nickytonline)
- [x] Update the spacing between the title and subtitle per the above design (@juliannatetreault)
- [x] Update the white space under the logo field so that it adjusts in size when a logo is uploaded, but otherwise it remains evenly spaced with the other elements on the form per the above design (@juliannatetreault)
- [x] Update the placement of the COC and TOS text and remove the italicization per the above design (@juliannatetreault)
- [x] Reduce the width of the form's layout to reduce its size per the above design (@juliannatetreault)
- [x] Remove italics from the "Community Name" placeholder (@juliannatetreault)

**Comment by juliannatetreault** [comment]
I'll tackle updating the COC and TOS text placement and the removal of its italicization (task 4 out 5)!

**Comment by juliannatetreault** [comment]
@nickytonline I was told that you were planning on tackling updating the radio buttons, is that correct? If so, I'll add your name by the task and will add you as an assignee to this issue!
