### ISSUE TITLE
Allow the logo to be uploaded via the admin 

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#15618]
**📖  As a Forem Creator, I need to be able to upload my logo on the admin interface, so that I have flexibility to change my logo when needed.** 

**🐣TASKS**

- [ ] Create an upload input on the admin 
- [ ] Re-use the Stimulus controller to preview the logo
- [ ] Allow the data to be saved to the admin Controller
- [ ] Re-use the Logo Uploader
- [ ] Show the preview of the image
