### ISSUE TITLE
Migrate `logo_svg` data

### ISSUE THREAD

**Issue by Ridhwana** [forem/forem#15620]
**📖  As a Forem Creator, that has been using Forem priori to the new onboarding process, I want my logo to be automatically updated based on the SVG provided without any manual intervention, so that my Forem continues to run as is without the UI breaking** 

**🐣TASKS**

- [x] Create a Data Update script to migrate the `logo_svg`
- [x] In the script add the svg+xml content to a file with an svg extension 
- [ ] strip any script tags
- [ ] Store the File using the `LogoUploader` class so that it goes through the necessary validations
- [ ] Test the script 
- [ ] Make a note to alert creators that if they using custom css on their logo it will no longer be available
