### ISSUE TITLE
Use forem/forem

### ISSUE THREAD

**Issue by tnir** [forem/forem#17208]
Use `https://github.com/forem/forem` (or just `forem/forem`) everywhere instead of `thepracticaldev/dev.to`:

- [x] package.json #17199
- [ ] Comments in Ruby (`*.rb`) #17319
   - https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/forem/forem%24+thepracticaldev/dev.to+lang:ruby+&patternType=literal
- [ ] Literals in Ruby (`*.rb`) #17320
- [ ] Code in shell scripts (`*.sh`) #17321
- [ ] Comments in JS (`*.js`)
   - https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/forem/forem%24+thepracticaldev/dev.to+lang:javascript+&patternType=literal
   - #17328
