### ISSUE TITLE
Epic - Member Index View: Invited Members

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17450]
This is the overarching tracking issue for progress on the "Invited members" section of Member Index View Phase 2

Tasks to complete:

- [x] https://github.com/forem/forem/issues/16226
- [x] https://github.com/forem/forem/issues/17451
- [x] https://github.com/forem/forem/issues/17452
- [ ] https://github.com/forem/forem/issues/17453
- [x] https://github.com/forem/forem/issues/17455

**Comment by mikeydorje** [comment]
Closing this epic tracker as stale bookkeeping. Most linked tasks were completed, and the remaining work is tracked in #17453, so this issue is no longer needed as a separate umbrella.
