### ISSUE TITLE
Epic - Member Index View: Member Index View Filters

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#17477]
⚠️ This is the overarching tracking issue for progress on the "Member Index View Filters" section of Member Index View Phase 2

📖 **As an Admin, I want my experience with filtering the Member Index View to be as pleasing and straightforward as possible, so that I feel motivated to use it.**

✅ Tasks to complete:
- [x] https://github.com/forem/forem/issues/17488
- [x] #17636
- [x] #17587
- [x] https://github.com/forem/forem/issues/17489
- [x] https://github.com/forem/forem/issues/17490
- [x] https://github.com/forem/forem/issues/17491
- [x] https://github.com/forem/forem/issues/17492
- [x] https://github.com/forem/forem/issues/17493
- [x] https://github.com/forem/forem/issues/17494
- [ ] https://github.com/forem/forem/issues/17495
- [x] https://github.com/forem/forem/issues/17496
- [ ] https://github.com/forem/forem/issues/18005
