### ISSUE TITLE
See who reacted to my posts

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#18125]
## Notes
This issue is blocked by #18277.

## User story 
📖 As an author, I should be able to see all people who reacted to my posts, and access their profiles.

To help authors see who has liked their post, we want to add a new piece of UI to the top of the post page. This UI is only visible to the **author** of the post. 

**[Design mockup:](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=803%3A1020)**

![likes and comment count](https://user-images.githubusercontent.com/84626054/183006689-d32acbdf-2a1f-4feb-a436-bc67d1272946.png)

**Interaction:**

<img width="618" alt="image" src="https://user-images.githubusercontent.com/84626054/187630469-5c36fc6f-86b0-4ffa-b875-584f067baf14.png">

**Design for the desktop modal:**

![With Comment](https://user-images.githubusercontent.com/84626054/187628808-ea7705a3-1531-44d3-a266-226324e39e0c.png)

Design for the mobile modal:

![list of users who have liked post, with a follow button](https://user-images.githubusercontent.com/84626054/180966876-d8f48d42-3df7-4838-b95d-20606bbc9251.png)

## Tasks

- [ ] Add the ability to fetch likes information for a post
- [ ] Create the modal, and show on button click
- [ ] Link the "X comments" text to the comments section

## Add the ability to fetch likes information for a post

Given there's the potential for thousands of likes on a post, I don't think we want to bundle the likes modal HTML into the server-generated page (especially since not all authors will open the modal on every visit). Instead we can fetch likes information via an API call whenever a user requests it (by clicking on the modal trigger button).

As far as I know, the current `reactions_controller` only delivers the total count of each reaction for a post. We need to be able to retrieve the following for all likes:

- Username
- Profile image
- Name
- User ID (for follow button)

Given there could be thousands of likes, we will want to paginate this data, and control the display of information via infinite scroll (see below).

Note: There are close similarities between this task and the related one on https://github.com/forem/forem/issues/18126 - whichever is created first can be re-used for the other.

 ## Create the modal, and show on button click

We can use the Preact modal, constructing the inner HTML with the data fetched from the backend. 

We will likely want these rows to appear in an infinite scroll, so that we don't need to load/generate thousands of rows when the modal is first opened. Current approaches to infinite scroll can be found in `initScrolling.js`.

Follow buttons will need to be initialised with the correct follow state - current code for this is in `followButtons.js`.

Quick note: be aware of the similarities between the modal in https://github.com/forem/forem/issues/18126 - whichever is tackled first can be re-used 🙂 

## Link the "X comments" text to the comments section

We will also display the number of comments to the author in this same UI section. The comments text should just link the author to the comments section, to save them from scrolling down.

Product point person: @amywtlin.

**Comment by pkfrank** [comment]
Let's begin this task by only making the list of reactors available to the **author** of the comment/post (and not a separate reader).

That information is already public to the author and thus we don't have to consider any privacy considerations (someone might reasonably expect their reaction to be private to everyone but the receiver).

**Comment by anujbhavsar96** [comment]
Assuming we will be removing the unicorn reaction option for now. This is how the interaction would look to see who reacted to my posts. 

![Jul-26-2022 14-04-07](https://user-images.githubusercontent.com/84626054/180962219-c3fa59b8-8628-4faa-a058-df0b3eca814d.gif)

Here are [Figma designs](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=701%3A2026) for it. 

**Mobile view**

| Default view  | Reaction modal |
| ------------- | ------------- |
| ![With Comment - Mobile](https://user-images.githubusercontent.com/84626054/180966856-da2c7472-73a3-4f63-b6dc-080e940cc602.png)  | ![Mobile version](https://user-images.githubusercontent.com/84626054/180966876-d8f48d42-3df7-4838-b95d-20606bbc9251.png)  |

NOTE: Only authors can check who reacted to their posts.

**Comment by mirie** [comment]
@anujbhavsar96 I am not a social tools aficionado AT ALL, so excuse the basic question: How will users know to click on the count? I couldn't tell that it was clickable looking at it -- maybe this is just something that users know/expect based on using tik tok, instagram, etc so **we're** kind of an oddball for _not_ making it clickable right now.

Also is this modal scrollable? What happens if there are 300 likes?

**Comment by anujbhavsar96** [comment]
> How will users know to click on the count? I couldn't tell that it was clickable looking at it. 

Yes. It doesn't look clickable right now since there is no visual change. It's new interaction. We can educate users about this unique interaction with a few methods.

1. DEV post about this new interaction
2. Product guide modal/tooltip once an author publishes their post

IMO the easiest way, for now, is to go for the DEV post. What do you think @pkfrank ?

**Comment by amywtlin** [comment]
I agree a dev.to post would be the most straightforward. We can just embed the video @anujbhavsar96 provided here. I think we should bundle this one and also the ability to see who react to my comment one, too.

**Comment by amywtlin** [comment]
As not everyone reads announcement posts, for discoverability, one thing we could consider is to adding a tooltip when users hover over the number of likes. @anujbhavsar96 how do you feel about this or something along this line?

**Comment by anujbhavsar96** [comment]
We can do that when the author is on the post-page ✨ I love how [Figma shows a walkthrough tooltip](https://assets.website-files.com/61a60c66d019df8b241b1720/62272bb99ba08964b7cb4e8b_SKbTg3_jm0qjg2k2DCRyLBrrhWkehA-JW5FkBtTffQImuU1hCCurfVXCXgfO4OVRSvYvS4jMbF01qQDuHsE4A7QlcdbJTHys8QkIkuOqKkh8StV-E_2I6I7b2d9jqSTiUzeacrkw.png) with graphics and tiny details. If we can do something similar, it will look great.

**Comment by aitchiss** [comment]
> As not everyone reads announcement posts, for discoverability, one thing we could consider is to adding a tooltip when users hover over the number of likes.

The only thing about a standard tooltip is that not all users can hover - anyone using a touch device will be missing this information 🙁 

> We can do that when the author is on the post-page ✨ I love how [Figma shows a walkthrough tooltip](https://assets.website-files.com/61a60c66d019df8b241b1720/62272bb99ba08964b7cb4e8b_SKbTg3_jm0qjg2k2DCRyLBrrhWkehA-JW5FkBtTffQImuU1hCCurfVXCXgfO4OVRSvYvS4jMbF01qQDuHsE4A7QlcdbJTHys8QkIkuOqKkh8StV-E_2I6I7b2d9jqSTiUzeacrkw.png) with graphics and tiny details. If we can do something similar, it will look great.

This is more of a 'contextual onboarding' - I don't think we've ever done anything like this in the app, but I know we've discussed a few times in the past it could be a nice thing to do. Like the iOS/android app banners, it could just disappear once acknowledged.

Naturally, there's a bit more dev effort involved in doing this so it would be good to know what is needed from product/design POV.


>  I couldn't tell that it was clickable looking at it -- maybe this is just something that users know/expect based on using tik tok, instagram, etc so we're kind of an oddball for not making it clickable right now

I feel the same @mirie 😄 For what it's worth, Twitter doesn't distinguish the number from the 'like' button.

I'm really curious though, is it important that a user can 'like' their own post? We already shipped changes to stop authors bookmarking their own post. I'm wondering if we could simplify things here and have a single "Like" button which _either_ opens the modal (if I'm the author) OR likes/unlikes the post (if I'm not the author)?

**Comment by amywtlin** [comment]
> The only thing about a standard tooltip is that not all users can hover - anyone using a touch device will be missing this information 🙁

@aitchiss What would be a good way for us to facilitate feature discovery for touch device users in general? Any recommendations?

>This is more of a 'contextual onboarding' - I don't think we've ever done anything like this in the app, but I know we've discussed a few times in the past it could be a nice thing to do. Like the iOS/android app banners, it could just disappear once acknowledged.
>
>Naturally, there's a bit more dev effort involved in doing this so it would be good to know what is needed from product/design POV.

Yea, I am aware of this. It is unlike usual feature implementation and tends to be more short-lived, hence requiring more maintenance than it should have needed. I do know there are 3rd-party integrations like [Chameleon](https://www.chameleon.io/) - supposedly it's all set with an one-time setup, and afterwards all can be handled in a web UI by non-devs. 

@pkfrank @mirie would we consider something like this for user onboarding? Contextual onboarding has proven to be much more effective for feature discovery. (well I don't have any studies handy but I know this from my own )

> I'm wondering if we could simplify things here and have a single "Like" button which either opens the modal (if I'm the author) OR likes/unlikes the post (if I'm not the author)?

@anujbhavsar96 what do you think?

**Comment by anujbhavsar96** [comment]
> I'm wondering if we could simplify things here and have a single "Like" button which either opens the modal (if I'm the author) OR likes/unlikes the post (if I'm not the author)?

Not sure about this. It might become a huge mismatch of interaction. On the other hand, as a reader, it works as Like, and as an author, it opens up modal. 

I have another idea ✨. How about we keep the left side action bar interaction as it is and include these two components with the post area? So clicking on 69 Likes opens up a modal with a list, and 10 Comments takes you to the comment area same as the left side comment icon. This is something that most platforms do to separate reactions and list of reactions. 

![With Comment](https://user-images.githubusercontent.com/84626054/183006689-d32acbdf-2a1f-4feb-a436-bc67d1272946.png)


> This is more of a 'contextual onboarding' - I don't think we've ever done anything like this in the app, but I know we've discussed a few times in the past it could be a nice thing to do. Like the iOS/android app banners, it could just disappear once acknowledged.
> 
> Naturally, there's a bit more dev effort involved in doing this so it would be good to know what is needed from product/design POV.

What if we open an information modal after they publish the post? Is it less dev effort or more? @aitchiss . It has more friction, but since it's one-time only and it contains feature information It should be fine.

**Comment by aitchiss** [comment]
> What would be a good way for us to facilitate feature discovery for touch device users in general? Any recommendations?

It's difficult in this case as the reactions in the actions bar have an established look/feel, and if we don't change how they look visually, there's probably not a great way to make the new functionality obvious (aside from the kind of contextual onboarding discussed here).

> I have another idea ✨. How about we keep the left side action bar interaction as it is and include these two components with the post area?

I love this! Having it top of the post like this will help draw attention to the new feature, and we also don't need to worry about differing functionality for the author/reader ✨ 

> What if we open an information modal after they publish the post? Is it less dev effort or more? @aitchiss . It has more friction, but since it's one-time only and it contains feature information It should be fine.

The complexity is tracking the state of whether the author has already seen this modal (so we don't show it every time they look at the post, but only directly after publishing). Would you want to show it every time they published a post, or just once? If just once then I think we'd need to track it in local storage, which would mean every time they switch browser they would see it again (like the mobile runtime banner). We could later remove the code, once we feel it's no longer necessary.

**Comment by aitchiss** [comment]
I've re-added the `needs design` tag as it sounds like we're leaning towards some kind of onboarding messaging for the feature / potentially adjusting where this info appears 🙂

**Comment by anujbhavsar96** [comment]
Based on the above discussion, the above post looks like the most appropriate position where we can display the Like count, which will open up the modal with a list of who reacted, instead of having it together with the Like action on the sidebar.

Since it's new UI addition, we might not need a feature discovery popup. Maybe just a DEV post might be enough.

@amywtlin @pkfrank thoughts on this?

**Comment by amywtlin** [comment]
@anujbhavsar96 I like this new approach! I think the new comment count introduced would also serve as a good alternative entry point that allow users get to the comment section when they are on desktop: #18127 

Anuj, as we have lots of discussions going on around this area simultaneously, please make sure we (at least you and I) have a final look at things to make sure if they are coherent and we can better decide the sequence of implementing these.

**Comment by aitchiss** [comment]
@amywtlin / @anujbhavsar96 - I've updated the description with what I think we've arrived at - does this all sound OK? Are we happy that this one is ready for dev?

**Comment by amywtlin** [comment]
@aitchiss I think so! Thank you, Suzanne.
