### ISSUE TITLE
Remove unicorn reactions

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#18277]
# Problem

The unicorn reactions, while being well-loved on DEV, can sometimes bring confusion to the users and it's not always on brand with all Forems. As we have discussed in several [Slack](https://forem-team.slack.com/archives/C03QCPEDDT3/p1658389672933249) [threads](https://forem-team.slack.com/archives/CAA200SH5/p1656305183488219?thread_ts=1655111706.931249&cid=CAA200SH5), we agree to remove the unicorn reactions for simplicity but think about how we can bring back the playfulness in a more customizable way at a later stage.

# To-dos

This is a list of things to do but needs some more pairs of eyes to check if these are exhaustive:
- Remove unicorn in all locations:
   - [x] Post page
   - [ ] Feed page
   - [ ] Notifications page (what do we show in place of the unicorn that happened in the past?)
   - [ ] `/dashboard/analytics` Reactions Summary :heart: 🦄 :bookmark: -> Also, there is a Unicorn legend in the graph
   - [ ] `/userID/some-post/stats` same as above
   - [ ] anywhere else?
- Handle legacy data
	- [ ] We need to recalculate all reactions and change how we show them

# Notes
1. As this involves lots of data recalculation, our overall strategy is that we will try to preserve old data for a while, instead of removing them for good all at once, in case there are scenarios we might want to consider using those data. 
2. This issue is a blocker to the following issues hence should be tackled first:
   - #18125 
   - #18127 

Product point person: @amywtlin.

**Comment by Link2Twenty** [comment]
😢

**Comment by aitchiss** [comment]
> anywhere else?

I can't see anywhere else in the code.

> Notifications page (what do we show in place of the unicorn that happened in the past?)

The notifications page only shows when someone has reacted to your comment/post with a unicorn, so if we remove the ability to react to these things with a unicorn, then it should (I think) be a straightforward UI code cleanup (if no new unicorn reactions arrive, then this UI shouldn't be triggered anyway 😄).

> We need to recalculate all reactions and change how we show them

I think we might want to solve this in the controllers, because going back through _all_ previous posts with unicorns and updating the reaction counts would be really expensive (might be good to get a backend perspective here).

For what it's worth, reaction counts on the post page are currently set in Javascript (in `app/assets/javascripts/initializers/initializeArticleReactions.js`), fetched from the `reactions_controller`. We could update the controller code to return the value of "likes" as `likes + unicorns`.

Similarly, in the `analytics_service.js` we could update the `calculate_reactions_totals` method to add unicorns and likes together. 

It feels a bit like a 'workaround' but it would avoid the need to update every single article that already has a unicorn reaction in the DB.

**Comment by amywtlin** [comment]
> My initial thought was just to convert all historical unicorn reactions to likes, and remove any duplicates.

Yes - this is my assumption, too. In other words, we consider both likes and unicorns as positive reactions, and after removing unicorns, we count # of users who left at least one reaction instead.

> This could be a large database operation, so we should make sure it's REALLY something we want to do not only on our Forems, but on Cloud and self hosted Forems as well!

Yes. Can confirm this is what we want across Forems, as unicorn reactions have been reported to confuse community members across Forems, and sometimes the branding doesn't match the image of a unicorn. Now that you mentioned this, I do think I need to write a post to announce we are making this change ahead of time on forem.dev, as it's quite a drastic change.

**Comment by amywtlin** [comment]
Tagging @maestromac for platform implications these recalculation might bring about (cc @pkfrank )

**Comment by joshpuetz** [comment]
I did notice that @aitchiss mentioned leaving the unicorns in place, and changing our application code to just add the two up. I'm going to investigate this as an intermediate step that wouldn't require data manipulation, but might not be as clear longer term.

**Comment by joshpuetz** [comment]
Update from Peter:

- We don't want to do any data manipulation (preserve all the older unicorn reactions!)
- We ok with data inconsistencies	
- We don't want a gap in the sidebar: we should merge this once https://github.com/forem/forem/issues/18127 is ready to go

Plan going forward:
- implement https://github.com/forem/forem/issues/18127 with a feature flag to swap between it and the unicorn button
- commit this PR to remove the unicorn and feature flag

**Comment by mirie** [comment]
Leaving this open as a reminder, but we have this https://github.com/forem/forem/issues/18521 as a continuation of the backend portion of the work. 

The remaining task of this work is to cleanup the feature flags implemented as well as remove unicorn as a hardcoded reaction.
