### ISSUE TITLE
Flaky tests - tracking

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18577]
We occasionally see errors in CI unrelated to changes in PRs that come up and sometimes break deployments on `main` as well. This issue is meant for tracking these and progressively work on them.

This issue doesn't require any core contributor nor community contributor to be assigned in order to start working on them. Any PR addressing these is welcome, but please link this issue in the PR so that it's visible for others 🙂 

------------

- [x] spec/models/ab_experiment/goal_conversion_handler_spec.rb:208

<details>

```
1) AbExperiment::GoalConversionHandler.call with user who is part of field test and user_creates_pageview goal records user_views_pages_on_at_least_four_different_hours_within_a_day field test conversionn

Failure/Error:
  expect(FieldTest::Event.pluck(:name))
    .to eq([goal, "user_views_pages_on_at_least_three_different_hours_within_a_day",
            "user_views_pages_on_at_least_four_different_hours_within_a_day"])

  expected: ["user_creates_pageview", "user_views_pages_on_at_least_three_different_hours_within_a_day", "user_views_pages_on_at_least_four_different_hours_within_a_day"]
      got: ["user_creates_pageview", "user_views_pages_on_at_least_two_different_days_within_a_week", "user_view...ree_different_hours_within_a_day", "user_views_pages_on_at_least_four_different_hours_within_a_day"]

  (compared using ==)

# ./spec/models/ab_experiment/goal_conversion_handler_spec.rb:208:in 'block (4 levels) in <main>'
# ./spec/rails_helper.rb:147:in 'block (3 levels) in <top (required)>'
# ./spec/rails_helper.rb:147:in 'block (2 levels) in <top (required)>'
# ./spec/rails_helper.rb:103:in 'block (2 levels) in <top (required)>'
```

</details>

- [ ] Logged out Home feed shows a profile preview card for an article's author

<details>

```
1) Logged out Home feed
       shows a profile preview card for an article's author:
     TestingLibraryElementError: Timed out retrying after 8000ms: Unable to find an accessible element with the role "link" and name "Admin McAdmin". There are no accessible roles. But there might be some inaccessible roles. If you wish to access them, then set the `hidden` option to `true`. Learn more about this here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole
```

</details>

- [ ] User visits articles by timeframe when user has logged in when viewing articles for infinity shows correct articles

<details>
1) User visits articles by timeframe when user has logged in when viewing articles for infinity shows correct articles
     Failure/Error:
       expect(page).to have_xpath(
         "//article[contains(@class, 'crayons-story') and not(contains(@class, 'crayons-story--featured'))]",
         count: count,
       )
       expected to find visible xpath "//article[contains(@class, 'crayons-story') and not(contains(@class, 'crayons-story--featured'))]" 4 times, found 3 matches
     # ./spec/system/articles/user_visits_articles_by_timeframe_spec.rb:16:in 'shows_correct_articles_count_via_xpath'
     # ./spec/system/articles/user_visits_articles_by_timeframe_spec.rb:162:in 'block (4 levels) in <main>'
     # ./spec/[secure]_helper.rb:147:in 'block (3 levels) in <main>'
     # ./spec/[secure]_helper.rb:147:in 'block (2 levels) in <main>'
     # ./spec/[secure]_helper.rb:103:in 'block (2 levels) in <main>'
     # ./spec/support/initializers/ci_csv_formatter.rb:92:in 'block (2 levels) in <main>'
```

</details>

 - [x] No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself

<details>

```
2022-10-11 13:10:06 +0000 Rack app ("POST /ahoy/events" - (127.0.0.1)): #<ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>
2022-10-11 13:10:06 +0000 Rack app ("GET /notificationsi=i" - (127.0.0.1)): #<ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>
2022-10-11 13:10:06 +0000 Rack app ("POST /ahoy/visits" - (127.0.0.1)): #<ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>
2022-10-11 13:10:06 +0000 Rack app ("GET /article_editor_v2_user/test-title-1fjb-temp-slug-7646894/editi=i" - (127.0.0.1)): #<ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>
2022-10-11 13:10:06 +0000 Rack app ("GET /article_editor_v2_user/test-title-1fjb-temp-slug-7646894/edit" - (127.0.0.1)): #<ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
>
      (Attempt 1 of 4) Maintains draft status when publishing a draft fails
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

</details>


- [ ] expected to find css ".runkit-element iframe" 1 time but there were no matches

<details>

```
1) Creating an article with the editor with Runkit tag creates a new article with a Runkit tag
     Failure/Error: expect(page).to have_css(".runkit-element iframe", count: count)
       expected to find css ".runkit-element iframe" 1 time but there were no matches

     # ./spec/support/runkit_tag_context.rb:12:in `expect_runkit_tag_to_be_active'
     # ./spec/system/articles/user_creates_an_article_spec.rb:51:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:154:in `block (3 levels) in <main>'
     # ./spec/rails_helper.rb:154:in `block (2 levels) in <main>'
     # ./spec/rails_helper.rb:110:in `block (2 levels) in <main>'
     # ./spec/support/initializers/ci_csv_formatter.rb:92:in `block (2 levels) in <top (required)>'
```

</details>


- [ ] New ones? Share them on a comment below 🙂

**Comment by heliocola** [comment]
@fdocr : FYI this exact same failure happened in the last 2 PRs: #18583 and #18584.
I was able to replicate this on my local machine and I will probably be able to identify the root cause.

I am still trying to identify the root cause but it fails depending on the values of the following factors/variables:
* The random timezone (defined by ZONEBIE_TZ) and
* the time the build runs.

I will spend a bit more time on this later on and I should be able to submit a PR.

**Comment by heliocola** [comment]
This issue also caused PRs #18604 and #18605 to fail on Travis.
This is happening because the data used to run the test is spamming multiple days, depending on the random timezone (selected by ZONEBIE_TZ) and the time the build runs.
This causes `user_views_pages_on_at_least_two_different_days_within_a_week` to also be included in the result.

There are 2 ways to solve this issue, that I've thought so far:
1. Change the seed data to ensure page_views `created_at` don't spam multiple days, so `user_views_pages_on_at_least_two_different_days_within_a_week` won't happen.
This has to consider UTC timezone (or the TZ for the date stored in the DB) because the code that aggregate this data uses `DATE(created_at)` which takes in consideration the date in the DB record, whichever TZ that date is stored.
Reference: https://github.com/forem/forem/blob/f68cb20d4c45b61e571d09975a12b39a301bb909/app/models/ab_experiment/goal_conversion_handler.rb#L69-L73

2. Change the expect clause from `eq` to `include` any of the following `"user_creates_pageview", "user_views_pages_on_at_least_three_different_hours_within_a_day", "user_views_pages_on_at_least_four_different_hours_within_a_day"`
There are other tests in this spec file that uses `include` instead of `eq`, so that would be an acceptable solution.

The data is created on these lines: https://github.com/forem/forem/blob/f68cb20d4c45b61e571d09975a12b39a301bb909/spec/models/ab_experiment/goal_conversion_handler_spec.rb#L203-L205
```
        7.times do |n|
          create(:page_view, user_id: user.id, created_at: n.hours.ago)
        end
```

@benhalpern : you touched the ab_experiment files recently, if you have any suggestion on how to approach, either from the options above, or another way you can think of, I'd be happy to submit a PR.

**Comment by fdocr** [comment]
Those are great details about the issue @heliocola 🙌🏼  Now that you mention this, what do you think about this other alternative 👇🏼 ?

Using [Timecop.freeze](https://github.com/travisjeffery/timecop#usage) (already in use on other specs) to ensure the date is always consistent. I'm not 100% sure what might work for this particular case, but we could pin it to UTC midday with something like `Time.current.utc.at_noon` ([at_noon](https://api.rubyonrails.org/classes/Date.html#method-i-at_noon)) or perhaps the same but [beginning_of_day](https://api.rubyonrails.org/classes/Date.html#method-i-beginning_of_day).

**Comment by heliocola** [comment]
@fdocr : what I intended to propose in the item 1 in my previous response is to do something line `Time.current.utc.at_noon` and use that to calculate `created_at` for the `page_view` objects with the current `7.times` and `n.hours.ago` thus ensuring all the page_views falls in the same day.

I believe `Timecop` can be used to freeze time at `Time.current.utc.at_noon`, but the fact time is frozen isn't adding much to the solution of the RED CI.

The way I see it, the problem causing the RED CI isn't about the time is changing, but the test data aren't created consistently with what the `expect(...) eq(...)` is looking for.
To ensure `user_views_pages_on_at_least_two_different_days_within_a_week` isn't part of the response, the test data must be within 1 day (based on the TZ stored in the DB - probably UTC).

**Comment by heliocola** [comment]
@fdocr : this issue can be closed now!
👍 to `Timecop.freeze` !

**Comment by fdocr** [comment]
Thanks @heliocola! There's a few other tests that fail occasionally and we can continue to keep track of them here for the time being. We are considering other tools to do this as well though, so I'll keep this one open for a bit longer

**Comment by fdocr** [comment]
Closing in favor of keeping track with [buildpulse](https://buildpulse.io/@forem/forem) dashboard
