### ISSUE TITLE
Multiple reactions V1 - Tracking issue

### ISSUE THREAD

**Issue by jaw6** [forem/forem#19008]
This issue is tracking a variety of bugs being reported in the [multiple reactions](https://github.com/forem/forem/issues/18808) internal testing. 

### Launch blocking issues:
* [x] Mobile view: Issues with long tap & text select
* [x] Mobile view: Count is blue?
* [x] Mobile view: Padding/margins (@lboogie04)
* [x] Screen ~600px, drawer should be above
* [x] Dark mode: drawer background highlight for active (@rt4914 )
* [ ] `next` `/notifications` needs new icons
* [x] `readinglist` should not toggle drawer button (@rt4914)
* [x] Remove dark circle highlight for drawer button+readinglist (@rt4914)
* [x] Remove `Add Reaction` tooltip [Reference](https://github.com/forem/forem/issues/19008#issuecomment-1404344776) (@rt4914)

![guide](https://user-images.githubusercontent.com/84626054/212811077-aa0f2830-2a2d-4c4d-bf8d-6731671e8aae.png)

### Non-blocking:
* [ ] Drawer could close faster when scrolling?
* [ ] Counter styling mismatch between drawer / comment / readinglist
* [ ] Timing issues on front-end when multiple reactions happen quickly
* [ ] Element alignment on `#index`
* [ ] `#index` colors (needs SVG unique)

`cc` @mirie @anujbhavsar96 @benhalpern @pkfrank 
:link: [Figma v1.1](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=988%3A3192), [feedback](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=807%3A906&t=5uLXPS6f6JnmM5JV-0)

**Comment by mirie** [comment]
@pkfrank - Can you review the list in the launch blockers and confirm them? I might have been out of the loop on conversations confirming this final list so I want to make sure we're focused on the absolute show stoppers to going live with this feature. Thanks!

**Comment by pkfrank** [comment]
Overall, this list looks pretty good in terms of the Blockers vs. Non-Blockers.

I want to call out two adjustments:

**Parity on index cards**: we should be at parity upon release.  Given the [potential complexity](https://github.com/forem/forem/issues/18641#issuecomment-1354996235) of that based on the rendering, I'm okay with treating (and any other index refinements) as a non-blocker and something we can take care of post-release.

**Tooltips**:  Per the exchange in #18641 and via Slack, let's remove the tooltip associated with the "main" icon that opens the drawer, but keep the tool tips associated with the individual reactions.  Picture below for clarity.


![picture detailing reactions and which to keep](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/E0uRO27q/b6d8e566-42da-48f2-b59f-19e7a9d34562.jpg?v=4dadc010b762dd7fd1f80d1ac19fafa0)

**Comment by anujbhavsar96** [comment]
Agree with Peter here. We can make the index card changes later. It's not a blocker

**Comment by jaw6** [comment]
I have updated the issue to de-emphasize `#index`.

---

@benhalpern 
> I notice we have the index view reactions showing up in the server-rendered cards, but not the JS-rendered cards. I wasn't sure if that was just a known WIP or not, but I don't see that here.

This was known and deliberate. Our feature flags are not currently accessible in JS, so we currently can only support this kind of testing in server-rendered views (unless/until we can somehow pass a flag to the client-side renderer -- we can _sometimes_ do this with CSS classes or `data-` attributes, but not always cleanly).

**Comment by mirie** [comment]
@jaw6 Looking to add more support to this so we can get to the finish line. Which items are appropriate for @rt4914 to help out with (either category)?

Anything else worth dividing and conquering on as a team?

**Comment by anujbhavsar96** [comment]
> /notifications needs new icons

@jaw6 @mirie @benhalpern @pkfrank  We can make one more change to clean up the notification for this issue. Right now, we display the multiple reaction icon in notifications based on the order we get the reaction. E.g., 🦄❤️🦄🦄❤️ . And with the increased types of reactions, this space can get too much overwhelming with lots of icons. 

To solve this, we can use one reaction icon for every unique reaction. Let's say the post has received 10 ❤️, 1🦄 and 5🔥. We can say 

> **Ben Halpern** and 10 others reacted to **All hands - Jan 24** with ❤️ 🦄 🔥

_This is not an ideal solution because it seems like **Ben Halpern and 10 others** reacted with all three ❤️ 🦄 🔥. But that might not be the case. Ben might have reacted with all three reactions, while I've reacted with Heart only. But it's better than what we have right now. Our current implementation also sounds same confusing._


Attaching mocks below
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/84626054/215045413-04473695-3565-4ba8-8faf-3594aabe99b3.png">

**Comment by mirie** [comment]
@jaw6 / @lboogie04 / @rt4914 -- would like to continue dividing and conquering on remaining bugs. @jaw6 can you provide some direction for @lboogie04 ? I know @rt4914 has been helping out, however I'm not clear on the issue how it's getting partitioned out / if @rt4914 has enough work too. Thanks!

**Comment by jaw6** [comment]
@lboogie04 @rt4914 There are three remaining issues:

* [ ] Mobile view: Padding/margins
* [ ] `readinglist` should not toggle drawer button
* [ ] Remove dark circle highlight for drawer button+readinglist

They are all up-for-grabs. (`notifications` turned out to be a deeper dive than I expected.)

**Comment by mirie** [comment]
@jaw6 I'd like to separate the non-launch blocking bugs into a separate issue. This is copied from the description above. Is this still the list? Anything to add / remove?

Non-blocking:

- [ ]  Drawer could close faster when scrolling?
- [ ]  Counter styling mismatch between drawer / comment / readinglist
- [ ]  Timing issues on front-end when multiple reactions happen quickly
- [ ]  Element alignment on #index
- [ ]  #index colors (needs SVG unique)

**Comment by jaw6** [comment]
That’s right 👍

**Comment by mirie** [comment]
https://github.com/forem/forem/pull/19061 is still open and unaddressed from this list. Re-assigning this issue to @lboogie04 as it is the last item remaining here.

**Comment by benhalpern** [comment]
Something I noticed here, which I imagine is an unintended inconsistency between dash and underscore @jaw6:

<img width="380" alt="Screen Shot 2023-02-13 at 5 49 27 PM" src="https://user-images.githubusercontent.com/3102842/218592187-3430f4a7-8520-42e8-8ac4-1eddabf128c0.png">

While this probably doesn't cause current bugs, seems like something which could bite us later if not addressed now?

**Comment by mirie** [comment]
@benhalpern going forward can we use https://github.com/forem/forem/issues/19064 to track bugs for multiple reactions,  OR if it is a truly launch blocker bug, please open a new bug issue. This issue is closed and I want to close this one for additional conversations
