### ISSUE TITLE
[Non-launch blockers] Multiple reactions V1 bugs

### ISSUE THREAD

**Issue by mirie** [forem/forem#19064]
This is the list pulled from https://github.com/forem/forem/issues/19008. It would be best to divide and conquest the following requests:

# Open bugs

- [ ] on single tap along with like reaction, open the drawer too so that user can see feedback for their action (see https://github.com/forem/forem/issues/19115 for more detail) --> captured in https://github.com/forem/forem/issues/19136

- [ ]   (@jaw6) In below image, the icons are in form of stack and the right most icon is on top but instead the leftmost icon should be on top and right most icon should be at bottom. (Not a deal-breaker as mentioned by @anujbhavsar96 )
<img width="329" alt="Screenshot 2023-02-08 at 12 19 33 PM" src="https://user-images.githubusercontent.com/9396084/217456353-d9e85bcc-c705-48cf-bfcb-fb694bf754e0.png"> --> captured in https://github.com/forem/forem/issues/19137 _(possibly already resolved)_

- [ ] Click different reactions and now remove all reactions. Notice that the heart+icon does not change to normal (unselected) icon. In below video notice that at 7/8 sec. --> captured in https://github.com/forem/forem/issues/19138

https://user-images.githubusercontent.com/9396084/217258985-cf87f1a9-d7e7-40ba-848f-f316c0477884.mov

- [ ] Multi-reactions are visible on the profile page article card and not visible on the index page. For consistency, we should remove it from the profile page and release it when it’s ready for both pages. --> captured here https://github.com/forem/forem/issues/19144

- [ ] Multi reaction drawer is not accessible via the Keyboard.
![Feb-16-2023 12-14-54](https://user-images.githubusercontent.com/84626054/219298674-26bf07d3-3b6c-4d16-ba5a-a9f6f8d66541.gif) --> captured in https://github.com/forem/forem/issues/19139

- [ ] Dark mode - Active reaction style adjustment. And the hover state is missing. Similar to 4th point.
<img width="966" alt="SCR-20230216-ia6" src="https://user-images.githubusercontent.com/84626054/219299165-8f1be25b-43ed-4300-bf7f-df6c054e3ef2.png"> --> captured in https://github.com/forem/forem/issues/19140

- [ ] The heart+ icon in inactive mode looks slightly bigger. Maybe it’s because of the wrong SVG. Otherwise, the size is perfect, 24*24px. Let me know if you need help exporting the correct SVG.
<img width="192" alt="image" src="https://user-images.githubusercontent.com/84626054/219299381-273ac762-8537-45a1-9e79-3f20da734adf.png"> --> captured in https://github.com/forem/forem/issues/19143

- [ ] The hover state is missing for reaction inside the reaction drawer. Just a little gray highlight.
<img width="1084" alt="SCR-20230216-ihu" src="https://user-images.githubusercontent.com/84626054/219301629-3f0e5fdc-be87-4872-97eb-5f58aebcaf57.png"> --> captured in https://github.com/forem/forem/issues/19140

# Resolved bugs
- [x] (@lboogie04) Close drawer when scrolling on the page or after clicking elsewhere on the page. [See more here](https://forem-team.slack.com/archives/C02C32DLPJP/p1674618049823349?thread_ts=1674578023.828969&cid=C02C32DLPJP). We can have an interaction where you click somewhere else on screen drawer closes. Please take a look at the similar interaction for the three-dot menu below the Save button. On clicking somewhere else on the screen, the dropdown menu closes. Also, when you open the drawer but start scrolling the page, it should trigger the drawer and close it.

![Image](https://user-images.githubusercontent.com/896728/216708528-66d1ff76-b4b2-4576-ad3b-bb30278fe79c.gif)

- [x]  (Assigned to @rt4914 #19077) Reaction Counter (Number) styling looks different for Reactions vs Comment and save. The number under Reactions is bolded

![Image](https://user-images.githubusercontent.com/896728/216706714-e8da4e02-039d-4458-82aa-a2006c569ea5.png)

- [x]  (Assigned to @rt4914 #19034) Remove the circle highlight styling for Reaction and Save. Our icon + color is enough to convey the active state. Please add screenshots for desktop/mobile when addressing and tag @anujbhavsar96 on the PR for a second look.

![Image](https://user-images.githubusercontent.com/896728/216707408-bfb069d2-8637-4f07-a376-c2755fac6685.png)

- [x]  (Assigned to @rt4914 #19077) Timing issues on front-end when multiple reactions happen quickly: While registering multiple reactions quickly, not all reactions flash on the **_left action toolbar_** (see where Heart+ icon is ---> it should update to last clicked on icon). We could remove this animation where we are flashing the Reaction icon on the left action toolbar to display the system response since we already have ringpop animation.

![Image](https://user-images.githubusercontent.com/896728/216707787-5f8d2158-9a2c-402e-bb3c-b9ba1befaed2.gif)

- [x]   (Assigned to @rt4914 #19079) Element alignment on #index. Example: https://forem.team/t/allhands (both regular and dark mode). The alignment looks off because of off the icons are aligned with the text. @anujbhavsar96 should the icons be vertically centered with the text?

![Image](https://user-images.githubusercontent.com/896728/216710015-c5b6de17-7feb-42a5-bde7-608594e048d2.png)

- [x] #index colors (needs SVG unique). The reaction icons look different on the actual Post vs on index pages. Example, compare [post](https://forem.team/jess/all-hands-jan-31-2h3d) vs [index page](https://forem.team/t/allhands).

Desired icon colors:
![Image](https://user-images.githubusercontent.com/896728/216710733-613cfd91-88d4-4d03-8b1f-072d24d107a4.png)

What it is currently looking like (wrong colors) on index page:
![Image](https://user-images.githubusercontent.com/896728/216710734-82e36fca-17f4-48fc-9b35-d47ea9713542.png)

- [x] (Assigned to @rt4914 #19079) The multi-reaction count is not a clickable button as a comment for the article card.

![Feb-08-2023 09-39-11](https://user-images.githubusercontent.com/84626054/217431421-2145878f-3c76-4fff-82ea-0db8f901681b.gif)

Link References:
- 🔗 Original [Figma v1.1](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=988%3A3192) designs
-  Design QA [feedback](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=807%3A906&t=5uLXPS6f6JnmM5JV-0)
- [Slack Thread](https://forem-team.slack.com/archives/C02C32DLPJP/p1674578023828969) with internal testing feedback

**Comment by mirie** [comment]
@anujbhavsar96 Moved the non-launch blockers to this issue. Can you take a pass through for the points I tagged you on for additional clarification. ALSO, if there are other items that are missing from this list, please add them~! I had a little trouble distinguishing in the various threads what was still pending, but hoping that this covers it all.

@lboogie04 and @rt4914: it would be great if you two can mob/split up this one as well 🙏

**Comment by anujbhavsar96** [comment]
> Close drawer faster when scrolling on the page or after clicking elsewhere on the page

[I don't mean closing it quickly](https://forem-team.slack.com/archives/C02C32DLPJP/p1674618049823349?thread_ts=1674578023.828969&cid=C02C32DLPJP). We can have an interaction where you click somewhere else on screen drawer closes. Please take a look at the similar interaction for the three-dot menu below the Save button. On clicking somewhere else on the screen, the dropdown menu closes.

Also, when you open the drawer but start scrolling the page, it should trigger the drawer and close it. This is not a dealbreaker though. 


> Element alignment on #index. Example: https://forem.team/t/allhands (both regular and dark mode). The alignment looks off because of off the icons are aligned with the text. @anujbhavsar96 should the icons be vertically centered with the text?

YES. They should be center aligned with text, the same as the comment icon + Add comment text. Also not sure if it's pointed out, but the Text color for `14 Reactions` and `Add Comment` is different. Reaction count text should have the same color styling as 'Add comment' text. `(--base-80 or #3d3d3d)`


---

I think this covers most. Most feedbacks are in this [Design QA](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=807%3A906&t=5uLXPS6f6JnmM5JV-0) feedbacks and [on Slack](https://forem-team.slack.com/archives/C02C32DLPJP/p1674578023828969). 

And, I am assuming [Design QA](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=807%3A906&t=5uLXPS6f6JnmM5JV-0) feedbacks are also WIP or done. cc @jaw6

**Comment by rt4914** [comment]
<img width="674" alt="Screenshot 2023-02-07 at 9 15 04 PM" src="https://user-images.githubusercontent.com/9396084/217330633-fdec19e2-1848-4603-8fc3-ef9b97900e0a.png">

In the above screenshot we can notice that the reactions related UI is different in both the articles. They should be same right? 
You can also notice this on https://forem.team/t/allhands have a look at 5,6,7,8 articles.

**Comment by anujbhavsar96** [comment]
Noticed another thing @mirie @jaw6, as displayed below, the multi-reaction count is not a clickable button as a comment for the article card.

![Feb-08-2023 09-39-11](https://user-images.githubusercontent.com/84626054/217431421-2145878f-3c76-4fff-82ea-0db8f901681b.gif)

**Comment by rt4914** [comment]
> Noticed another thing @mirie @jaw6, as displayed below, the multi-reaction count is not a clickable button as a comment for the article card.
> 
> ![Feb-08-2023 09-39-11](https://user-images.githubusercontent.com/84626054/217431421-2145878f-3c76-4fff-82ea-0db8f901681b.gif) [ ![Feb-08-2023 09-39-11](https://user-images.githubusercontent.com/84626054/217431421-2145878f-3c76-4fff-82ea-0db8f901681b.gif) ](https://user-images.githubusercontent.com/84626054/217431421-2145878f-3c76-4fff-82ea-0db8f901681b.gif) [ ](https://user-images.githubusercontent.com/84626054/217431421-2145878f-3c76-4fff-82ea-0db8f901681b.gif)

@anujbhavsar96 Added this to issue description as a task

**Comment by mirie** [comment]
@jaw6 For what @rt4914 pointed out [here](https://github.com/forem/forem/issues/19064#issuecomment-1421240035), do you know what might be causing this? At first I thought perhaps because the Articles didn't have any new reactions, that was causing the discrepancy, but then I compared 2 feed tabs and can see a different output for the same article. 

https://forem.team/t/allhands and https://forem.team/t/allhands/latest

**Relevant:**
![Image](https://user-images.githubusercontent.com/896728/217948863-aa13c287-9ced-4a2e-ae56-a6e314d4c580.png)

**Latest:**
![Image](https://user-images.githubusercontent.com/896728/217948862-13e23113-045b-41b8-acc6-2d343cdc656a.png)

**Comment by anujbhavsar96** [comment]
Something is causing these alignment issues. @mirie @rt4914 @jaw6 

**1. Alignment of icon and count above article title.** 
<img width="401" alt="SCR-20230213-cup" src="https://user-images.githubusercontent.com/84626054/218365772-34888b9b-5078-4933-81ed-1796ea6831ee.png">

**2. In notifications, the reaction icon is not in-line with the text line.**
<img width="410" alt="SCR-20230213-cvz" src="https://user-images.githubusercontent.com/84626054/218365972-eabc1f9d-d065-4994-bc3a-9c6d9938a817.png">

In both cases, the icon should be horizontally aligned with adjacent text.

**Comment by rt4914** [comment]
> Something is causing these alignment issues. @mirie @rt4914 @jaw6
> 
> **1. Alignment of icon and count above article title.** <img alt="SCR-20230213-cup" width="401" src="https://user-images.githubusercontent.com/84626054/218365772-34888b9b-5078-4933-81ed-1796ea6831ee.png">
> 
> **2. In notifications, the reaction icon is not in-line with the text line.** <img alt="SCR-20230213-cvz" width="410" src="https://user-images.githubusercontent.com/84626054/218365972-eabc1f9d-d065-4994-bc3a-9c6d9938a817.png">
> 
> In both cases, the icon should be horizontally aligned with adjacent text.

Fixing this is https://github.com/forem/forem/pull/19107

**Comment by benhalpern** [comment]
Now that the initial mobile interaction is fixed, I believe it has revealed another bug, which I think might be a misunderstanding in expected behavior.

I thought the reason we wanted to go long-press to open the drawer is so that a tap would result in the _default reaction_ (i.e. "like"), and the long press would be what is required to open the drawer.

Current behavior: Tap does nothing, long press opens the drawer. This is weird behavior because now "long press" is the _only_ interaction.

Expected behavior: Click (i.e. tap in mobile) should always trigger the default reaction. I think this can/should apply in all scenarios, but is especially important on touch screens, where the "hover" isn't a shortcut to all options.

There might be room for interpretation here, but I think this is what the functionality needs to be. @anujbhavsar96 @rt4914 would you agree?

**Comment by rt4914** [comment]
I do agree @benhalpern 
I think there are two possible solutions:
1. As mentioned by you, i.e. single-tap marks the default like reaction and long press opens the drawer.
2. Long press is completely removed and single tap opens the drawer directly.

What its worth, I personally believe 1st option is better as we can get the reaction from user in **1 tap** or **1-long-tap + another tap**
as compared to second which always require **2-taps**.

**Comment by benhalpern** [comment]
@rt4914 I also believe **1** is the best option, and is the original intention which we _are really close to_. The long press is working nicely, and closing the loop on the whole functionality by triggering the behavior on click of the original icon seems appropriate.

This also maximally preserves _existing_ functionality and expectations while augmenting for new functionality. If we are to add multi-reactions to comments, per se, we would do well to preserve the click-as-default-reaction.

This is the Facebook behavior which we are also looking to mimic as the "standard" here.

I think this is important to get right before switching live, but I think we're just about there.

***

One last thing: I think the "long press" is _a tiny bit too long_. Shortening by ~200ms or so would be good, IMO. I know this is the definition of small concerns, but if this is easy enough to play with, I'd advocate for adjusting it down just a bit.

**Comment by jaw6** [comment]
@benhalpern sounds to me like those (tap -> heart & shorter long tap) should be separate issues then?

**Comment by benhalpern** [comment]
@jaw6 Yeah, I'd say so.

And apologies, I think I brought this up in the wrong place.

I think the "tap for heart" _is_ a blocking bug because the current mobile usability is diminished too much when "tap does nothing".

I believe this should be added here: https://github.com/forem/forem/issues/19008

But from my current perspective, that's it. We're _this close_.

The "shorter long tap" thing is pretty subjective, and doesn't need to be a blocker if it is non-trivial, or disagreed-upon from other product perspectives.

cc: @pkfrank and @mirie

**Comment by mirie** [comment]
Captured the blocking bug for tap / long press in https://github.com/forem/forem/issues/19115

Moving this issue back to in progress as there are two unaddressed non-launch blocking bugs.

**Comment by anujbhavsar96** [comment]
It seems like things have been concluded, but I also agree with option 1, where tap=default reaction and long press=open drawer.

I also feel the drawer opening duration is a little long.

**Comment by anujbhavsar96** [comment]
All the interaction works like a charm 🔥

Just a few non-blocking nitpicks,

1. Multi-reactions are visible on the profile page article card and not visible on the index page. For consistency, we should remove it from the profile page and release it when it’s ready for both pages.

2. Multi reaction drawer is not accessible via the Keyboard.
![Feb-16-2023 12-14-54](https://user-images.githubusercontent.com/84626054/219298674-26bf07d3-3b6c-4d16-ba5a-a9f6f8d66541.gif)

3. Dark mode - Active reaction style adjustment. And the hover state is missing. Similar to 4th point.
<img width="966" alt="SCR-20230216-ia6" src="https://user-images.githubusercontent.com/84626054/219299165-8f1be25b-43ed-4300-bf7f-df6c054e3ef2.png">


3. The heart+ icon in inactive mode looks slightly bigger. Maybe it’s because of the wrong SVG. Otherwise, the size is perfect, 24*24px. Let me know if you need help exporting the correct SVG.
<img width="192" alt="image" src="https://user-images.githubusercontent.com/84626054/219299381-273ac762-8537-45a1-9e79-3f20da734adf.png">


4. The hover state is missing for reaction inside the reaction drawer. Just a little gray highlight.
<img width="1084" alt="SCR-20230216-ihu" src="https://user-images.githubusercontent.com/84626054/219301629-3f0e5fdc-be87-4872-97eb-5f58aebcaf57.png">

**Comment by jaw6** [comment]
@mirie 
> For what @rt4914 pointed out here, do you know what might be causing this? At first I thought perhaps because the Posts didn't have any new reactions, that was causing the discrepancy, but then I compared 2 feed tabs and can see a different output for the same article. 

Sorry, took a little time to confirm what I was seeing, but I (sort of?) know why this is happening.

While they appear nearly identical on the surface, `/t/allhands/latest` and `/latest` are served from totally different controllers with very different output rendering processes. In effect, `/latest` is very similar to `/` (the home page), in that content is rendered client-side for logged-in users.

`/t/allhands/latest` is being served out of `Stories::TaggedArticlesController` and uses a distinct `index` template, but it re-uses some post partials from `articles`. The first page is rendered fully server-side (so it gets the multiple reactions, even for logged-in users) but there's an "infinite scroll"-type pattern, where it retrieves a new "page" of articles every time you reach the end, and that page is being entirely rendered client-side, thus has the simple-reactions template.

I don't have any guesses for why these controllers look alike but behave very differently, I don't know if there's a reason we're mixing client- and server-side rendering, or how much work would be involved in straightening this all out (rough guess: a _lot_) -- but I don't think we _have_ to, at this stage, to get this launched. 

We're also talking about this in Slack, but I think we turn the `articles#index` partials back to simple-reactions style, launch with simpler (but consistent) `index` views, then have a separate issue/PR to update all the `index` templates, both client- and server-side. It'll be a slightly bumpier roll-out than we might prefer, but having already worked out a bunch of kinks in the `index` view ("stacks"), it should be less bumpier than it _could_ have been.

**Comment by mirie** [comment]
Forgot to close this now that I've separated the items out into separate issues
