### ISSUE TITLE
Remove background image as part of /onboarding config

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19412]
## Is this feature related to a problem? Please describe.

As a Forem Admin, I want the background design of `/onboarding` to look clean and appealing without additional configuration.

In addition, as the creator of the Forem platform, we want the default configuration to be simplified so as to not overwhelm the Forem Admin with various configurations that can be burdensome to manage effectively.

## Describe the solution you’d like

Remove the background image option as part of `/onboarding`. This concerns removing it from the Admin > Customization > Config > Onboarding UI, removing the application logic and data, and also coming up with a new background design idea for `/onboarding`.

**This task should start as a design exploration to finalize the new look.**  We can then proceed into updating the UI, logic, and data layer.

**Design solution** : [Figma Designs](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?type=design&node-id=2434-19415&t=boOnQK6YYswUr4Bm-4)

Replace the background image with branded gradient background. We have logic defined to find darker shades of branded color. For DEV we can use `indigo-600` as the brand color and `indigo-900` as the brand color - darkest shade.

Apart from that, we will have to remove the overlay background behind the modal. Below is the image dispalying how it would look for different Forems with different brand colors.

![Final](https://github.com/forem/forem/assets/84626054/a7954c5c-ae39-4dfc-8786-f8c936ad70ab)

## Definition of Done

**Task 1: Design exploration for new background look**

- [x] Anuj to explore new design ideas for the `/onboarding` background.
- [x] Take into account the "Brand Color" defined in Admin > Config > User Experience & Brand and incorporate it into the new design.

**Task 2: Update UI, logic, and data layer**

- [ ] Remove the “background image URL” field from Admin > Config > Onboarding
- [ ] Update the database schema to remove any tables or fields associated with the background image configuration. 

**Task 3: Implement the new background design**

- [ ] Based on the finalized design idea from Task 1, implement the new background design for `/onboarding`

## Additional Context

This is one of several issues collectively aimed at cleaning up the Onboarding to require fewer configurations and better defaults.

**Comment by anujbhavsar96** [comment]
@pkfrank Added the designs in the solution and removed the `needs design` tag. 

cc @mirie

**Comment by mirie** [comment]
I have a question about this -- 

- Is the goal of this change to increase the number of self-hosted Forems? 
- Do we find the background image to be overwhelming to the new user and thus causing dropoff in our onboarding flow? If that's the case, is there a easier way (such as updating the current image on DEV) to test this hypothesis?

I think the gradient backgrounds are visually appealing, however I feel like I'm missing the reason/strategy to investing in engineering work on this relative to other work that could move the needle on engagement.

**Comment by pkfrank** [comment]
@mirie

The goal of this issue is to continue cleaning up the `/onboarding` experience for new members as well as for Forem Admins.  We've taken on similar work over the past few weeks in https://github.com/forem/forem/issues/19413 and https://github.com/forem/forem/issues/19414 which make the overall administration more intuitive, and introduces better "defaults" so that we don't get bogged down in micro-configurations.

With regards to DEV, we could test this hypothesis by changing the background image under the current system, but this is a change we want to make for all Forems to have a cleaner and more consistent design (and to reduce configuration burden).

While this change may not have an immediate impact on growth or revenue, it contributes to the long-term sustainability and success of Forems.  It's also not a particularly large initiative (especially b/c we've already invested in and completed the design exploration), and will fit alongside the other Onboarding work we've taken on recently.

**Comment by dukegreene** [comment]
I've sketched out the preliminary steps of the refactor to try and connect the dots between the primary brand color setting and the UI. 

As I approach the "draw background gradient" step, I see that the styling is happening in a Preact component render (`app/javascript/onboarding/Onboarding.jsx ll.70-93`) and our best programmatic work for darkening colors lives on the backend in our Color::CompareHex service and its #brightness method.

The draft PR is up at https://github.com/forem/forem/pull/19815, I'll dig back into this on Monday, possibly with a pair
