### ISSUE TITLE
Remove manually suggested users as part of /onboarding config

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19413]
## Is this feature related to a problem?  Please describe.

As a Forem Admin, I want the suggested users that are displayed in `/onboarding` to reflect the most relevant and high quality authors that the platform has to offer.

In addition, as the creator of the Forem platform, we want the default configuration to be simplified so as to not overwhelm the Forem Admin with various configurations that can be burdensome to manage effectively.

## Describe the solution you’d like

We already have logic in the Forem application which chooses “suggested users” to display in `/onboarding` based on factors such as the tags the new member selected, the recent activity of the suggested users, etc.

This issue speaks directly to removing the concept of **manually suggested users**.

This issue touches on:

1. Removing the UI (text input and checkbox) from Admin > Config > Onboarding for manually suggested users; and
2. Removing the underlying logic and data

Upon completion, the “suggested users” functionality in the application should purely rely on the fallback suggestions without any need/ability to define “manually suggested users.”

We should implement this change in such a way that it does not cause any problems on any Forem that does currently use the “manually suggested users” functionality.

## Definition of Done

**Task 1: Remove UI for manually suggested users**

- [ ] Remove unneeded elements from Admin > Config > Onboarding
    - [ ] Remove text input area for usernames
    - [ ] Remove checkbox for manually suggested users

**Task 2: Remove underlying logic and data for manually suggested users**

- [ ] Remove data fields used to store and retrieve the manually suggested users.
- [ ] Remove logic responsible for handling manually suggested users

**Task 3: Ensure fallback suggestions continue to work properly based on current factors** (edited)

- [ ] Ensure that the fallback suggestions, based on existing factors, continue to function properly.
- [ ] Ensure that this change does not create issues for Forems that **do** currently use this feature

## Additional Context

This is one of several issues collectively aimed at cleaning up the Onboarding to require fewer configurations and better defaults.

We'll create a separate issue that details a task for updating logic to define when this screen shows up in `/onboarding` (IE it won't show up for _brand new Forems_).
